spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:mysql://localhost:3306/rossmille_db?useSSL=false&serverTimezone=America/Bogota&allowPublicKeyRetrieval=true
    username: RossMille
    password: RossMillB01
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false

server:
  port: 8080

jwt:
  secret: rossmille-jwt-secret-key-2024-rossmille-pos-web
  expiration: 28800000
